spring.application.name=CentralMed

# Conexao com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/centralmed_db
spring.datasource.username=centralmed_user
spring.datasource.password=centralmed_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#para aliviar erro de compatibilidade entre as versoes do jdk e spring
spring.main.allow-circular-references=true
